const cPanelTutorials = [
    { label: 'cPanel Tutorial 1'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
    { label: 'cPanel Tutorial 2'},
    { label: 'cPanel Tutorial 3'},
];

export default cPanelTutorials;