const wordpressTutorials = [
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
    { label: 'WordPress Tutorial 1'},
    { label: 'WordPress Tutorial 2'},
    { label: 'WordPress Tutorial 3'},
];

export default wordpressTutorials;